import 'server-only'
import { randomBytes } from 'crypto'
import * as argon2 from 'argon2'
import { readFile, writeFile, rename } from 'fs/promises'
import { join } from 'path'

/**
 * Generate a cryptographically secure random token
 * Returns URL-safe base64 string (43 chars for 32 bytes = 256 bits entropy)
 */
export function generateSecureToken(length: number = 32): string {
  const buffer = randomBytes(length)
  return buffer.toString('base64url')
}

/**
 * Generate a session secret (same as generateSecureToken, semantic alias)
 */
export function generateSessionSecret(length: number = 32): string {
  return generateSecureToken(length)
}

/**
 * Hash a token using argon2id with OWASP recommended parameters
 * - memoryCost: 19456 (19 MiB)
 * - timeCost: 2 iterations
 * - parallelism: 1 thread
 * - hashLength: 32 bytes output
 */
export async function hashToken(token: string): Promise<string> {
  return argon2.hash(token, {
    type: argon2.argon2id,
    memoryCost: 19456,
    timeCost: 2,
    parallelism: 1,
    hashLength: 32,
  })
}

/**
 * Verify a token against a stored hash (timing-safe via argon2)
 */
export async function verifyToken(token: string, hash: string): Promise<boolean> {
  try {
    return await argon2.verify(hash, token)
  } catch {
    return false
  }
}

/**
 * Check if this is a first-run scenario (no admin configured)
 * Returns true if .env.local doesn't exist or has no ADMIN_TOKEN_HASH
 */
export async function isFirstRun(): Promise<boolean> {
  try {
    const envPath = join(process.cwd(), '.env.local')
    const content = await readFile(envPath, 'utf-8')
    return !content.includes('ADMIN_TOKEN_HASH=')
  } catch (error) {
    // ENOENT = file doesn't exist = first run
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return true
    }
    // Other errors: assume first run for safety
    return true
  }
}

/**
 * Admin configuration to save to .env.local
 */
export interface AdminConfig {
  tokenHash: string
  firstName: string
  lastName: string
  email: string
  sessionSecret: string
}

/**
 * Save admin configuration to .env.local
 * - Reads existing content
 * - Removes any existing ADMIN_* and SESSION_SECRET lines
 * - Appends new config block
 * - Writes atomically (temp file + rename)
 */
export async function saveAdminConfig(config: AdminConfig): Promise<void> {
  const envPath = join(process.cwd(), '.env.local')
  const tempPath = join(process.cwd(), '.env.local.tmp')

  let existingContent = ''
  try {
    existingContent = await readFile(envPath, 'utf-8')
  } catch {
    // File doesn't exist yet, start fresh
  }

  // Filter out existing admin config lines
  const lines = existingContent
    .split('\n')
    .filter(line => {
      const trimmed = line.trim()
      return !trimmed.startsWith('ADMIN_') &&
             !trimmed.startsWith('SESSION_SECRET=') &&
             !trimmed.startsWith('# Admin Configuration')
    })

  // Remove trailing empty lines
  while (lines.length > 0 && lines[lines.length - 1].trim() === '') {
    lines.pop()
  }

  // Add new config block
  lines.push('')
  lines.push('# Admin Configuration (generated by setup wizard)')
  lines.push(`ADMIN_TOKEN_HASH="${config.tokenHash}"`)
  lines.push(`ADMIN_FIRST_NAME="${config.firstName}"`)
  lines.push(`ADMIN_LAST_NAME="${config.lastName}"`)
  lines.push(`ADMIN_EMAIL="${config.email}"`)
  lines.push(`SESSION_SECRET="${config.sessionSecret}"`)
  lines.push('')

  // Write atomically: temp file then rename
  const newContent = lines.join('\n')
  await writeFile(tempPath, newContent, 'utf-8')
  await rename(tempPath, envPath)
}
